version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.23.2
        environment:
          NODE_ENV: "production"

    working_directory: ~/backend-coding-test

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run build

      - run: npm run test

      - store_test_results:
          path: test-results

